Update README.md
isaachinman/next-i18next pull request #1142
Opened 2021-04-12 16:07 UTC by eraygundogmus

Changes mentioned in [1132](https://github.com/isaachinman/next-i18next/issues/1132)

2021-04-14 11:03 UTC, isaachinman requested changes

2021-04-14 11:03 UTC, isaachinman commented on README.md
> +## How it works?
```suggestion
## How does it work?
```

2021-04-14 11:03 UTC, isaachinman commented on README.md
> +The `next-i18next.config.js` file that we use in the set up acts as a wrapper by providing the configuration between next-i18next, i18n, and NextJs.
```suggestion
Your `next-i18next.config.js` file will act as a wrapper, providing configuration for `next-i18next`, `i18next`, and NextJs.
```

2021-04-14 11:03 UTC, isaachinman commented on README.md
> +
I think this can be greatly simplified or removed, as all of this is already explained in later sections of the documentation.

2021-04-14 11:03 UTC, isaachinman commented on README.md
> +// This function gets called at build time on server-side. For more information, please read Next.js docs.
I think this should be removed.

2021-04-14 11:03 UTC, isaachinman commented on README.md
> +import { serverSideTranslations } from "next-i18next/serverSideTranslations";
```suggestion
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
```

2021-04-14 11:03 UTC, isaachinman commented on README.md
> +}
Should be removed.

2021-04-14 15:56 UTC, eraygundogmus commented on README.md
> +
It's up to you, I think simplifying is better

2021-04-14 15:57 UTC, eraygundogmus reviewed
All done

2021-04-15 10:39 UTC, isaachinman commented on README.md
> +
Not sure I get your point – in my view, repeating ourselves in the documentation is not simplifying anything.

2021-04-15 16:00 UTC, eraygundogmus commented on README.md
> +
In the setup section, this content you mentioned is described under separate headings. These might be hard to get noticed because most people only look at blocks of code in the installation sections. I believe this section is important because it gives a summary. I prefer to simplify if we have two options, such as removing it completely or simplifying it. I'd suggest it stay that way, but I respect your opinion. I'll work on it and commit changes.
I recomen

2021-04-24 13:18 UTC, eraygundogmus reviewed
Why and How is simplified.

2021-05-06 19:36 UTC, eraygundogmus commented
@isaachinman can you review it?

2021-05-07 08:31 UTC, isaachinman commented on README.md
> +Easy to set up, easy to use: setting up only takes a few steps, and configuration is simple.
```suggestion
Easy to set up, easy to use: setup only takes a few steps, and configuration is simple.
```

2021-05-07 08:31 UTC, isaachinman commented on README.md
> +After configuration, `appWithTranslation` allows us to use `i18n` and `t` function in our components through props.
```suggestion
After configuration, `appWithTranslation` allows us to use the `t` (translate) function in our components via hooks.
```

2021-05-07 08:31 UTC, isaachinman commented on README.md
> +Then we add `serverSideTranslation` inside [getStaticProps](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation) or [getServerSideProps](https://nextjs.org/docs/basi
```suggestion
Then we add `serverSideTranslation` to [getStaticProps](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation) or [getServerSideProps](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering) (depending on your case) in our page-level components.
```

2021-05-07 08:31 UTC, isaachinman commented on README.md
> +After this process, we will be able to translate our NextJs app on the client side.
```suggestion
Now our NextJs app is fully translatable!
```

2021-05-07 08:31 UTC, isaachinman commented on README.md
> +}
I prefer a `const` + arrow function, so this should be removed.

2021-05-07 08:31 UTC, isaachinman commented on README.md
> +}
Again, should be removed.

2021-05-07 08:31 UTC, isaachinman commented on README.md
> -
Needs an empty line at the end of file.

2021-05-07 10:46 UTC, eraygundogmus commented
@isaachinman All resolved, i guess.

2021-05-14 15:53 UTC, eraygundogmus reviewed
.

2021-05-17 13:07 UTC, isaachinman requested changes
Thanks @eraygundogmus – just about ready!

2021-05-17 13:07 UTC, isaachinman commented on README.md
> +Then we add `serverSideTranslation` to [getStaticProps](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation) or [getServerSideProps](https://nextjs.org/docs/basic-fe
```suggestion
After configuration, `appWithTranslation` allows us to use the `t` (translate) function in our components via hooks.

Then we add `serverSideTranslation` to [getStaticProps](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation) or [getServerSideProps](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering) (depending on your case) in our page-level components.
```

2021-05-17 14:37 UTC, isaachinman approved these changes

2021-05-17 14:37 UTC, merged