Fix CVE-2021-23346 vulnerability
isaachinman/next-i18next pull request #1144
Opened 2021-04-12 23:26 UTC by MAOKG

* update react-i18next to 11.8.13 to fix [CVE-2021-23346](https://github.com/i18next/react-i18next/issues/1275)

2021-04-13 10:09 UTC, isaachinman requested changes

2021-04-13 10:09 UTC, isaachinman commented on examples/simple/yarn.lock
> +  uid ""
These changes should be removed.

2021-04-13 14:06 UTC, MAOKG commented on examples/simple/yarn.lock
> +  uid ""
Oh, it's added by yarn when running `yarn test`. Should I remove all the changes on `examples/simple/yarn.lock`? 

My yarn version is 1.22.10

2021-04-13 14:08 UTC, isaachinman commented on examples/simple/yarn.lock
> +  uid ""
You can leave the other changes, but the `next-i18next` entry should not be changed.

2021-04-13 14:32 UTC, MAOKG commented on examples/simple/yarn.lock
> +  uid ""
Thanks, @isaachinman, I just pushed the update

2021-04-16 15:31 UTC, MAOKG commented
@isaachinman Can you have another look when you have time? Hopefully, this change will get released soon, [CVE-2021-23346](https://github.com/i18next/react-i18next/issues/1275) is blocking us from consuming `next-i18next`. Thanks in advance!

2021-04-19 11:03 UTC, isaachinman approved these changes

2021-04-19 11:10 UTC, merged