fix: Make appWithTranslation generic over AppProps type
isaachinman/next-i18next pull request #1514
Opened 2021-11-10 12:22 UTC by petarvujovic98

Add support for proper custom App component types

2021-11-10 12:46 UTC, petarvujovic98 commented
Closes #1348

2021-11-10 16:34 UTC, isaachinman requested changes

2021-11-10 16:34 UTC, isaachinman commented on src/appWithTranslation.tsx
> +  WrappedComponent: React.ComponentType<Props> | React.ElementType<AppProps>,
```suggestion
  WrappedComponent: React.ComponentType<Props> | React.ElementType<Props>,
```

To answer your question about why we need `ElementType` – it's just for the sake of comprehensiveness. See the type def:

```ts
type ElementType<P = any> =
  {
      [K in keyof JSX.IntrinsicElements]: P extends JSX.IntrinsicElements[K] ? K : never
  }[keyof JSX.IntrinsicElements] |
  ComponentType<P>;
```

2021-11-10 18:11 UTC, petarvujovic98 commented on src/appWithTranslation.tsx
> +  WrappedComponent: React.ComponentType<Props> | React.ElementType<AppProps>,
The reason that I asked in the first place is because of the following error when providing ElementType with a generic type parameter like `Props` in our case
![Screenshot_10-11-2021_19:11:20](https://user-images.githubusercontent.com/36507050/141169534-4876cefe-20e1-49bc-b616-c75488b4570b.png)
![Screenshot_10-11-2021_19:09:49](https://user-images.githubusercontent.com/36507050/141169392-3c54d8ee-7d6b-4a73-915c-e2b7ba539d07.png)

2021-11-10 18:24 UTC, isaachinman commented on src/appWithTranslation.tsx
> +  WrappedComponent: React.ComponentType<Props> | React.ElementType<AppProps>,
OK, I'm fine with just using `React.ComponentType<Props>`, but we'll need to wait for the v9 release to publish a change like that (should be this week).

If you're happy with that, please change the target of your PR to: https://github.com/isaachinman/next-i18next/pull/1512

2021-11-10 18:28 UTC, petarvujovic98 commented on src/appWithTranslation.tsx
> +  WrappedComponent: React.ComponentType<Props> | React.ElementType<AppProps>,
I don't have any problem with that

2021-11-11 10:05 UTC, isaachinman approved these changes

2021-11-11 10:05 UTC, merged