feat: Expose Translation react-i18next component
isaachinman/next-i18next pull request #1609
Opened 2022-01-04 11:41 UTC by myrjola

These changes export the [react-i18next Translation component](https://react.i18next.com/latest/translation-render-prop) from the next-i18next module. I found this component the best match for introducing translations in the [Page.getLayout]( https://nextjs.org/docs/basic-features/layouts#per-page-layouts) function. The useTranslation hook is [not allowed because the getLayout function is not top-level](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level).

I also added test coverage for the Translation component by using it on the second page to render the header. It's tested by `yarn test:e2e`.

2022-01-04 16:58 UTC, kachkaev commented on examples/simple/pages/second-page.js
> +        </Translation>
Re-exporting the component won’t harm but I’m not sure if `<Translation>` should become a part of the example.

Render props and HOCs are are deprecated pattern and can be substituted with hooks in modern react apps. Those who don’t understand this distinction well may look at the example and end up with a more complex syntax than they otherwise could.

2022-01-04 17:32 UTC, myrjola commented on examples/simple/pages/second-page.js
> +        </Translation>
Thanks for bringing the deprecation to my attention! Where is it documented? I could not see any deprecation notice on https://react.i18next.com/latest/translation-render-prop.

I wonder what would be a better approach if I would need translations in the [Next.js getLayout pattern](https://nextjs.org/docs/basic-features/layouts#per-page-layouts).

Specifically, I'd like to translate the page title. Since getLayout is not a React component but a function, I can't use the useTranslation hook. Instead of using `<Translation>`, would it make sense to pass the t function to the getLayout function as a parameter?

```jsx
export default function MyApp({ Component, pageProps }) {
  const { t } = useTranslation()

  // Use the layout defined at the page level, if available
  const getLayout = Component.getLayout || ((page) => page)

  return getLayout(<Component {...pageProps} />, t)
}
```

```jsx
Page.getLayout = function getLayout(page, t) {
  return (
    <Layout>
      <Head>
        <title>{t('pageTitle')}</title>
      </Head>
      <NestedLayout>{page}</NestedLayout>
    </Layout>
  )
}
```

2022-01-04 18:00 UTC, kachkaev commented on examples/simple/pages/second-page.js
> +        </Translation>
I don’t know if HOCs and render props were deprecated ‘officially’ anywhere. They achieve the same results as hooks do, and are used much less these days.

In your `getLayout` pattern you can get access to `useTranslation()` as long as you call it inside some component:

```tsx
function MyCoolLayout() {
  const t = useTranslation()
 
  return (
    <Layout>
      <Head>
        <title>{t('pageTitle')}</title>
      </Head>
      <NestedLayout>{page}</NestedLayout>
    </Layout>
  )
}

Page.getLayout = function getLayout(page, t) {
  return (
    <MyCoolLayout>{page}</MyCoolLayout>
  )
}
```

Not sure if `<Head><title>{t('pageTitle')}</title></Head>` belongs to the layout, but that’s outside this PR scope.

2022-01-05 06:56 UTC, myrjola commented on examples/simple/pages/second-page.js
> +        </Translation>
I removed the changes to second-page.js to not set a bad example. Regarding test coverage, I think we don't have coverage for the <Trans> component either, but we can probably rely on react-i18next to work as it should.

> In your getLayout pattern you can get access to useTranslation() as long as you call it inside some component:

Yes! Separating <Head> to its own component is cleaner. Thank you!

2022-01-09 07:20 UTC, isaachinman approved these changes
Looks good, we just need CI to run. Circle should be building forked PRs, so not sure why the status checks haven't come back. You can try pushing an empty commit.

Thanks @myrjola!

2022-01-10 09:11 UTC, myrjola commented
Thank you for a great package @isaachinman! I pushed a new commit, but it seems the codeclimate and node-multi-build checks are not running. It seems that this other PR also has the same issue https://github.com/isaachinman/next-i18next/pull/1593

Is there something wrong with the Circle CI integration?

2022-01-10 11:19 UTC, isaachinman commented
Not sure @myrjola, but it appears something is indeed wrong for forked PRs. I've regenerated the CircleCI ssh key – do you mind trying again? Thanks!

2022-01-11 10:04 UTC, isaachinman requested changes
Apologies for not catching this before, I was travelling during the holidays. [This file](https://github.com/isaachinman/next-i18next/blob/master/src/types.ts) will need to be updated for TS users. Unfortunately we're still maintaining types manually.

2022-01-11 10:41 UTC, myrjola commented
Added the Translation export to the types.ts file.

2022-01-11 11:11 UTC, isaachinman approved these changes

2022-01-11 11:11 UTC, merged

2022-01-11 11:11 UTC, isaachinman commented
Thanks @myrjola!