Add required Next.js version to README
isaachinman/next-i18next pull request #819
Opened 2020-09-04 01:16 UTC by valuegrammer

i wax trying to use next-i18next with a project i was working on but couldn't quite get locale subpaths working properly 

after some investigation it turns out i had nextjs version 9.3 which doesnt support rewrites and that took me quite a while to notice

So i added extra information to the read me to prevent others from falling in the same pitfall

2020-09-04 06:26 UTC, juzhiyuan commented on README.md
> +2. Create a `next.config.js` file inside your root directory if you want to use locale subpaths. You can see this approach in the [examples/simple/next.config.js](./examples/simple/next.config.js) **
`Next.js 9.5 or higher` would be better

2020-09-04 12:13 UTC, valuegrammer commented on README.md
> +2. Create a `next.config.js` file inside your root directory if you want to use locale subpaths. You can see this approach in the [examples/simple/next.config.js](./examples/simple/next.config.js) **
Yeah that's right i'll change it when i get on my computer

2020-09-05 16:42 UTC, valuegrammer commented
Alright made it more concise @juzhiyuan

2020-09-06 00:44 UTC, juzhiyuan commented
Just waiting for Admin's review :D

2020-09-07 15:41 UTC, isaachinman requested changes

2020-09-07 15:41 UTC, isaachinman commented on README.md
> +2. Create a `next.config.js` file inside your root directory if you want to use locale subpaths. You can see this approach in the [examples/simple/next.config.js](./examples/simple/next.config.js) **
Please change to `(Next.js v9.5+ required)`.

2020-09-07 23:09 UTC, valuegrammer commented on README.md
> +2. Create a `next.config.js` file inside your root directory if you want to use locale subpaths. You can see this approach in the [examples/simple/next.config.js](./examples/simple/next.config.js) **
Done.

2020-09-08 01:37 UTC, juzhiyuan commented on README.md
> +2. Create a `next.config.js` file inside your root directory if you want to use locale subpaths. You can see this approach in the [examples/simple/next.config.js](./examples/simple/next.config.js) **
v9.5+ please

2020-09-08 02:17 UTC, valuegrammer commented on README.md
> +2. Create a `next.config.js` file inside your root directory if you want to use locale subpaths. You can see this approach in the [examples/simple/next.config.js](./examples/simple/next.config.js) **
that's what i did?
Am i getting you right i'm pretty sure that's what i did

2020-09-08 02:26 UTC, juzhiyuan commented on README.md
> +2. Create a `next.config.js` file inside your root directory if you want to use locale subpaths. You can see this approach in the [examples/simple/next.config.js](./examples/simple/next.config.js) **
![image](https://user-images.githubusercontent.com/2106987/92426936-bcfc8480-f1bd-11ea-91cc-a8705d39b4e4.png)

2020-09-08 04:38 UTC, valuegrammer commented on README.md
> +2. Create a `next.config.js` file inside your root directory if you want to use locale subpaths. You can see this approach in the [examples/simple/next.config.js](./examples/simple/next.config.js) **
https://github.com/valuegrammer/next-i18next
that's what it says.... i'm confused

2020-09-09 00:23 UTC, isaachinman commented on README.md
> +2. Create a `next.config.js` file inside your root directory if you want to use locale subpaths. You can see this approach in the [examples/simple/next.config.js](./examples/simple/next.config.js) **
I'm asking you to literally change the text to read `(Next.js v9.5+ required)`.

2020-09-10 10:13 UTC, isaachinman approved these changes

2020-09-10 10:13 UTC, merged