Handles "cimode" correctly
isaachinman/next-i18next pull request #851
Opened 2020-10-09 12:46 UTC by andfk

As reported before #510 "cimode" is not getting handled correctly, so i've made some small changes for that to work. 

What does "cimode"? It just returns the key requested to the "t" function as explained [here](https://www.i18next.com/overview/api#changelanguage)

Thanks for this library :)

2020-10-09 13:36 UTC, isaachinman commented
Looks like you'll need to bump the bundlesize limit.

2020-10-09 17:42 UTC, andfk commented
Yeah @isaachinman i see. Now is changed.

2020-10-10 10:40 UTC, isaachinman requested changes

2020-10-10 10:40 UTC, isaachinman commented on src/utils/is-cimode.ts
> +export const isCIMode = (language: string) => language === 'cimode'
Needs a newline at end of file.

2020-10-10 10:40 UTC, isaachinman commented on src/utils/is-cimode.ts
> +// Detects if in CI mode due language used
Can we get some basic test coverage for this util?

2020-10-10 10:40 UTC, isaachinman commented on src/config/create-config.ts
> +    return combinedConfig
Can you explain why this bailout is necessary?

2020-10-12 08:11 UTC, andfk commented on src/config/create-config.ts
> +    return combinedConfig
Yes, this is main the reason and why this PR exists. If you set "cimode" without this condition, the server side, will try to resolve "cimode" namespace files, which is wrong

2020-10-12 08:32 UTC, andfk commented on src/utils/is-cimode.ts
> +// Detects if in CI mode due language used
Super simple test added anyway i wonder i should i add more test cases like in `create-config` or asset if the client really returns the keys when in cimode

2020-10-12 12:11 UTC, isaachinman commented on src/config/create-config.ts
> +    return combinedConfig
Well, if your aim is to remove the filesystem checks, you should do that directly, instead of bailing out of the entire procedure.

2020-10-12 19:33 UTC, andfk commented on src/config/create-config.ts
> +    return combinedConfig
I already tried in a past commit to by pass the server & client setup, anyway im not a fan of that nested flow condition (even codeclimate fails). Whats your main concern? "cimode" has an specific target where we just want to get the translation key, nothing more so i think no "extra config" is required. Im wrong? Please let me know.

2020-10-13 15:47 UTC, isaachinman approved these changes

2020-10-13 15:47 UTC, isaachinman commented on src/config/create-config.ts
> +    return combinedConfig
Sure, we can proceed with this. What you've said makes sense.

2020-10-13 15:48 UTC, merged

2020-10-13 15:49 UTC, andfk commented
thanks @isaachinman