Allow fallbackLng to be set to false
isaachinman/next-i18next pull request #862
Opened 2020-10-21 22:35 UTC by sverps

Setting fallback language to defaultLanguage in production should only occur if the developer didn't specifically set it to `false`, since that would be a valid config for i18next.

This fix will make it possible to avoid loading any fallback translation files, which could speed up page load.

2020-10-26 10:49 UTC, isaachinman requested changes

2020-10-26 10:49 UTC, isaachinman commented on src/config/create-config.ts
> +  if (userConfig.fallbackLng === undefined) {
Can we do something like `typeof !== "boolean"`?

2020-11-05 23:00 UTC, sverps commented on src/config/create-config.ts
> +  if (userConfig.fallbackLng === undefined) {
I made a commit with the requested change

2020-11-06 13:46 UTC, isaachinman approved these changes

2020-11-06 13:46 UTC, merged