feat: add typescript example
isaachinman/next-i18next pull request #928
Opened 2021-01-30 12:20 UTC by franzmoro

This is a leftover from the [original PR](https://github.com/isaachinman/next-i18next/pull/922) addressing missing TS types. It adds a typescript example.

Used default `tsconfig.json` created when running `yarn dev` straight after having created the Next.js app with `npx create-next-app`. I could be up to the dev(s) to modify this config by themselves.

2021-01-31 13:41 UTC, isaachinman commented
My main concern with adding other examples has always been maintenance. However, I think TS is so mainstream now, that I would actually consider just making the main example TS, as the source code itself isn't too different.

What are your thoughts?

2021-02-02 16:20 UTC, franzmoro commented
The code of the 2 examples is virtually the same, yes.
I agree also on TS being mainstream, but still a lot of teams don't use it. I'm not sure if having just the TS example becomes confusing, as JS is supported of course.

I'm happy to keep both, but I'm not too opinionated about it - just trying to help. LMK.

2021-02-06 15:52 UTC, isaachinman requested changes

2021-02-06 15:52 UTC, isaachinman commented on examples/with-typescript/components/Footer.tsx
> +export const Footer: React.FC<{}> = () => {
The generic argument is unnecessary – you can just write `React.FC =`.

2021-02-06 15:52 UTC, isaachinman commented on examples/with-typescript/components/Header.tsx
> +interface Props {
Let's use `type` over `interface ` in all cases.

2021-02-06 15:52 UTC, isaachinman commented on examples/with-typescript/package.json
> +  "name": "v10",
Name should be something like `next-i18next/examples/with-typescript`.

2021-02-06 15:52 UTC, isaachinman commented on examples/with-typescript/pages/index.tsx
> +const Homepage = () => {
Needs `React.FC`.

2021-02-06 15:52 UTC, isaachinman commented on examples/with-typescript/pages/second-page.tsx
> +const SecondPage: React.FC<{}> = () => {
Again, unnecessary generic arg can be dropped.

2021-02-11 08:20 UTC, sethreidnz commented on examples/with-typescript/pages/_app.tsx
> +import { appWithTranslation } from 'next-i18next'
Why is this called appWithTranslation? When I try to import this in my TS project like this I get:

```
'"../../node_modules/next-i18next/types"' has no exported member named 'appWithTranslation'. Did you mean 'AppWithTranslation'?
```

2021-02-11 08:22 UTC, sethreidnz commented on examples/with-typescript/pages/_app.tsx
> +import { appWithTranslation } from 'next-i18next'
It looks like the original example has a file `i18n.js` that it imports this function from. But in this example that file doesn't exist... and this function is being imported from `next-i18next` how does that work?

2021-02-11 08:26 UTC, sethreidnz commented on examples/with-typescript/pages/_app.tsx
> +import { appWithTranslation } from 'next-i18next'
Ahh I get it now, this is part of a new beta version.

2021-02-12 12:32 UTC, danielrakoczyas commented on examples/with-typescript/components/Header.tsx
> +export const Header: React.FC<Props> = ({ title }) => (
HeaderProps

2021-02-24 16:05 UTC, closed without merging