feat: Disable FS backend when user provides one
isaachinman/next-i18next pull request #930
Opened 2021-01-31 20:02 UTC by filipesmedeiros

One thing to note is that it seemed necessary to make the changes to the way we handle the passing of the config to the client.
Next cannot serialize stuff like functions, so we cannot return everything and assume it's serializable, especially the `use` array and the `backend` prop (with the props inside).
The way this was done now requires the user to pass the same config to `appWithTranslation` that they pass to `serverSideTranslations`. This is kind of repetitive and limiting (same client side config for the whole app). We could allow the user the to pass a function that decides what config to use based on the current page, but that seems troublesome.

Let me know what you think!

2021-02-04 11:28 UTC, LeonardDrs commented
Tried this modification on my app, it works really well.
Dunno if you've seen my edit to this [comment](https://github.com/isaachinman/next-i18next/issues/931#issuecomment-772686669) but I didn't had to pass the configuration myself to `serverSideTranslations` and the `sprintf-postProcessor` worked just fine in SSG/SSR

2021-02-05 18:09 UTC, filipesmedeiros commented
Your comment, doesn't it mean you gotta have `next-i18next.config.js` inside `src`? Or was it outside?

2021-02-05 18:20 UTC, LeonardDrs commented
Nop, `next-i18next.config.js` is right beside `package.json` and `next.config.js` on the root of the project

2021-02-21 18:28 UTC, filipesmedeiros commented
I will rebase this is the branch with the new changes @isaachinman just merged

2021-02-21 18:30 UTC, isaachinman commented
Sounds good, thanks!

2021-02-21 20:00 UTC, isaachinman requested changes

2021-02-21 20:00 UTC, isaachinman commented on src/createClient/node.ts
> +    if (!hasCustomBackend)
Let's use curly braces here, please.

2021-02-21 20:00 UTC, isaachinman commented on types.d.ts
> +
Shouldn't be necessary.

2021-02-21 20:08 UTC, filipesmedeiros commented on src/createClient/node.ts
> +    if (!hasCustomBackend)
Sure thing!

2021-02-21 20:08 UTC, filipesmedeiros commented on types.d.ts
> +
My bad, removed

2021-02-21 20:48 UTC, isaachinman approved these changes

2021-02-21 20:48 UTC, merged