Adds useTranslation hook example of usage
isaachinman/next-i18next pull request #940
Opened 2021-02-10 09:31 UTC by zarabotaet

Due
https://github.com/isaachinman/next-i18next/issues/814#issuecomment-688382104

2021-02-11 14:28 UTC, isaachinman approved these changes

2021-02-11 14:28 UTC, isaachinman commented
Needs a semantic title. Thanks @zarabotaet!

2021-02-14 11:34 UTC, zarabotaet commented
> Needs a semantic title. Thanks @zarabo

2021-02-15 10:26 UTC, zarabotaet commented
> Needs a semantic title. Thanks @zarabotaet!

done

2021-02-15 12:23 UTC, isaachinman requested changes

2021-02-15 12:23 UTC, isaachinman commented on README.md
> + const {t} = useTranslation('footer')
Can you add spaces around the `t` destructure?

2021-02-15 14:06 UTC, isaachinman approved these changes

2021-02-15 14:06 UTC, merged